name: dart_extensionz
description: A set of Dart extensions I use in various projects. Including Boolean, DateTime extensions and more.
version: 10.1.0
repository: https://github.com/mj12358/dart-extensionz
screenshots:
  - description: Dart Extensionz Thumbnail
    path: assets/thumbnail.png
funding:
  - https://www.buymeacoffee.com/mj12358
topics:
  - dart
  - extension

environment:
  sdk: ">=3.13.3 <4.0.0"

dependencies:
  intl: ^0.20.3

dev_dependencies:
  # dart run coverage:test_with_coverage
  coverage: 1.15.1
  dart_lintz: 2.2.0
  file: 7.0.1
  path: 1.9.1
  test: 1.32.0
