name: Create Tag

on:
  push:
    paths:
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  create_tag:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read pubspec.yaml
        id: pubspec
        uses: nichmor/minimal-read-yaml@v0.0.2
        with:
          config: "./pubspec.yaml"

      - name: Get Tag
        run: |
          echo "NEW_TAG=v${{ steps.pubspec.outputs['version'] }}" >> $GITHUB_ENV

      - name: Create and Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
